# General settings
name: 'sample'      # Warning: 'debug' and 'test' are reserved name that have a special behavior
wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch

resume: null            # If resume, path to ckpt file from outputs directory in main directory
# test_only: /home/nico/projects/SparseDiffArchitecture/outputs/2025-12-07/22-00-30-train/checkpoints/train/last.ckpt # baseline after 100
test_only: /home/nico/projects/SparseDiffArchitecture/outputs/2025-12-17/16-00-07-train/checkpoints/train/last.ckpt # baseline after 200
# test_only: /home/nico/projects/SparseDiffArchitecture/outputs/2025-12-15/14-14-53-finetune/checkpoints/finetune/last.ckpt # finetune after 100, all t, odds=0.1, no y
# test_only: /home/nico/projects/SparseDiffArchitecture/outputs/2025-12-14/14-54-22-finetune/checkpoints/finetune/last.ckpt # finetune after 100, all t, odds=0.1, with y
test_variance: 1
generated_path: null    # path of generated samples, this file should be of pickle type

check_val_every_n_epochs: 10
sample_every_val: 10
val_check_interval: null
samples_to_generate: 10       # We advise to set it to 2 x batch_size maximum
samples_to_save: 10
chains_to_save: 10
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 10
final_model_samples_to_save: 10
final_model_chains_to_save: 10

evaluate_all_checkpoints: False

# sampling parameters
skip: 1
log_violations: True                      # whether to log the violations
pdm_strategy: "last"                      # when to apply PDM during sampling: "never", "always", "last" 
connected: True                           # whether to enforce connectivity during projection
planar: True                              # whether to enforce planarity during projection
max_weight: 0                            # sum of all edge weights per graph must be below this value, 0 means no limit
