defaults:
    - _self_
    - general : finetune_custom
    - model : model_finetune_custom
    - train : negative_sampling_custom
    - dataset : custom

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}
