# Training settings
n_epochs: 100
batch_size: 4
lr: 0.0002
clip_grad: null          # float, null to disable
save_model: True
num_workers: 8
progress_bar: true
weight_decay: 1e-12
optimizer: adamw
seed: 0
